language: node_js
node_js:
  - 12
before_script:
  - npm install @11ty/eleventy -g && npm i
deploy:
  fqdn: ryandudek.com
  local-dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: develop
